### ISSUE TITLE
Cannot create RepositoryFile due to `"sha" wasn't supplied. []`

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-github#26] opened 2020-05-01 17:36 UTC
```
pulumi up -s LinioIT/global
Previewing update (LinioIT/global):
     Type                            Name                 Plan
     pulumi:pulumi:Stack             api-skeleton-global
 +   └─ github:index:RepositoryFile  mergeable            create

Resources:
    + 1 to create
    10 unchanged

Do you want to perform this update? yes
Updating (LinioIT/global):
     Type                            Name                 Status                  Info
     pulumi:pulumi:Stack             api-skeleton-global  **failed**              1 error
 +   └─ github:index:RepositoryFile  mergeable            **creating failed**     1 error

Diagnostics:
  pulumi:pulumi:Stack (api-skeleton-global):
    error: update failed

  github:index:RepositoryFile (mergeable):
    error: PUT https://api.github.com/repos/LinioIT/api-skeleton/contents/.github/mergeable.yml: 422 Invalid request.

    "sha" wasn't supplied. []

Resources:
    10 unchanged

Duration: 11s
```

**Comment by nesl247** [comment] 2020-05-08 14:52
https://github.com/terraform-providers/terraform-provider-github/issues/438

**Comment by charlex** [comment] 2020-09-20 16:38
I've bumped into this too, just to give context on impact.

**Comment by mikhailshilkov** [comment] 2023-08-09 21:05
Unfortunately, the link to the upstream issue doesn't work anymore. Since the issue is three years old, received no additional comments and has no repro, I'll close it as non-actionable

**Closed by mikhailshilkov** 2023-08-09 21:05 UTC
Labels: kind/bug, resolution/no-repro
